### ISSUE TITLE
[Feature request] Make it possible to inject kubernetes secrets into the locust worker pods

### ISSUE THREAD

**Issue by pmacik** [AbdelrhmanHamouda/locust-k8s-operator#149]
**Is your feature request related to a problem? Please describe.**
I'd like to have secrets (such as tokens) available in the locust files to be used in the API calls

**Describe the solution you'd like**
The idea here is to create a `Secret` with the tokens in the locust namespace and point the `LocustTest` to that `Secret` (similarly as the locust file is mounted from `ConfigMap`. The controller would then mount the `Secret` to the worker pods (either as env variables or as a files) and the locust files executed by the workers would then be able to get those tokens from env variables (or by reading the mounted files).

**Describe alternatives you've considered**
Currently, I need to hard-code the tokens into the locust file directly.

**Additional context**
n/a

**Comment by PaulRudin** [comment]
I think more generally it would be useful to allow arbitrary additions/override of the pod spec for the workers and master. That's much more flexible and would address this and all sorts of other things people might reasonably want. 

The nitty gritty of the details need to be decided - but one very reasonable approach would be to merge according to do a json merge patch as per: https://datatracker.ietf.org/doc/html/rfc7396.

**Comment by treenerd** [comment]
Hello,

I like use external-secrets operator and vault to manage secrets.
So in my case I tend use Environment variables inside the container and the locust files read the environment variables with standard python libraries. 
[web_ui_auth](https://github.com/locustio/locust/blob/f4d0300c49a1926d9552ddbde75748fda32e9d4f/examples/web_ui_auth.py#L45)

If the operator would support to create environment variables from secrets, this would be helpful.
With GitOPS workflows and the useage of tools like ArgoCD, I prefer to avoid to have credentials in configmaps.
I like how this is implemented in [cloudnative-pg](https://cloudnative-pg.io/documentation/1.22/declarative_role_management/#password-management) to give an example.

```
 managed:
    users:
    - name: loadtest-user1
      ensure: present
      passwordSecret:
        name: loadtest-user1
```

Just my thoughts on this topic.

**Comment by namiyousef** [comment]
In addition to the above, it would be immensely helpful to be able to inject environment variables into the locust and metrics exporter pods. At the moment this is not possible which makes using the operator a bit tricky for custom use-cases.

**Comment by AbdelrhmanHamouda** [comment]
Hey @pmacik, @PaulRudin, @treenerd, @namiyousef, @M4C4R, @Spritekin — thank you all for your patience on this feature request!

I have some good news! 

First and for most; I repeat my appreciation for taking the time to spend time on this and help me make the project better. After a lot of contemplation, i decided to bite the bullet and rewrite the operator in Go as the problems i was getting with Java was too much for me to keep this going along side my work and personal life. Also some design choices that were done before made it very hard to end the operator to support more use cases. I tried my best to accommodate your input on this and i hope the result meets your expectations and **i'm more than happy to receive feedback**! 

I'm excited to share that **environment variable and secret injection is fully implemented in V2** of the operator.

## What's Supported

The V2 API (`locust.io/v2`) now supports **four different methods** for injecting secrets and configuration:

### 1. ConfigMap Environment Variables
Inject all keys from a ConfigMap as environment variables with an optional prefix:

```yaml
apiVersion: locust.io/v2
kind: LocustTest
metadata:
  name: my-test
spec:
  # ... other fields ...
  env:
    configMapRefs:
      - name: app-config
        prefix: "APP_"  # Optional prefix
```

### 2. Secret Environment Variables
Inject all keys from a Secret as environment variables:

```yaml
env:
  secretRefs:
    - name: api-credentials
      # Optional prefix available here too
```

This addresses @pmacik's original request and @treenerd's need for GitOps-friendly secret management with tools like external-secrets-operator and Vault.

### 3. Individual Environment Variables
Fine-grained control over specific variables with literal values or references:

```yaml
env:
  variables:
    - name: TARGET_HOST
      value: "https://api.example.com"
    - name: API_TOKEN
      valueFrom:
        secretKeyRef:
          name: api-secret
          key: token
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: password
```

This addresses @Spritekin's request for standard Kubernetes `env` syntax and @namiyousef's need for custom environment variables.

### 4. Secret File Mounts
Mount secrets as files in the container (perfect for TLS certificates, JSON key files, etc.):

```yaml
env:
  secretMounts:
    - name: tls-certs
      mountPath: /etc/locust/certs
      readOnly: true
```

This addresses @pmacik's question about supporting both environment variables AND file mounts.

## Complete Example

Here's a real-world example combining multiple methods:

```yaml
apiVersion: locust.io/v2
kind: LocustTest
metadata:
  name: load-test-with-secrets
spec:
  image: locustio/locust:2.20.0

  master:
    command: "--locustfile /lotest/src/locustfile.py --host https://api.example.com"

  worker:
    command: "--locustfile /lotest/src/locustfile.py"
    replicas: 5

  testFiles:
    configMapRef: locust-scripts

  env:
    # All keys from ConfigMap with prefix
    configMapRefs:
      - name: app-config
        prefix: "APP_"

    # All keys from Secret (no prefix)
    secretRefs:
      - name: api-credentials

    # Individual variables
    variables:
      - name: ENVIRONMENT
        value: "production"
      - name: SPECIAL_TOKEN
        valueFrom:
          secretKeyRef:
            name: vault-secret
            key: token

    # Mount secrets as files
    secretMounts:
      - name: tls-certs
        mountPath: /etc/locust/certs
        readOnly: true
```

Then in your locustfile:

```python
import os

# Access environment variables
api_token = os.getenv('API_TOKEN')
db_password = os.getenv('DB_PASSWORD')
target_host = os.getenv('APP_TARGET_HOST')

# Read mounted certificate files
import ssl
ssl_context = ssl.create_default_context(cafile='/etc/locust/certs/ca.crt')
```

## Documentation

Full documentation is available at:
- **How-To Guide:** [Inject secrets and configuration](https://abdelrhmanhamouda.github.io/locust-k8s-operator/how-to-guides/security/inject-secrets/)
- **API Reference:** [EnvConfig spec](https://abdelrhmanhamouda.github.io/locust-k8s-operator/api_reference/#envconfig)
- **Sample CRs:** See `config/samples/locust_v2_locusttest_with_env.yaml` in the repo

## About Arbitrary Pod Spec Overrides

Regarding @PaulRudin suggestions to allow arbitrary pod spec additions/overrides with JSON merge patch. This is a powerful idea, but I've taken a slightly more structured approach for now:

- **Environment variables:** Full support (as shown above)
- **Volume mounts:** Supported via `spec.volumes` and `spec.volumeMounts` with target selection (master/worker/both)
- **Scheduling:** Supported via `spec.scheduling` (affinity, tolerations, nodeSelector)
- **Resources:** Supported via `spec.master.resources` and `spec.worker.resources`

The approach provides better validation, clearer error messages, and easier upgrades. If there are specific pod spec fields you need that aren't currently supported, please open a new feature request and I can evaluate adding them!

## Migration from V1

You'll need to migrate to V2 to use these features. The V2 API is the storage version and represents the future of the operator. See the [Migration Guide](https://abdelrhmanhamouda.github.io/locust-k8s-operator/migration/) for details.

## Closing Thoughts

This has been a highly requested feature with great feedback from you 😄 . The implementation supports all the use cases mentioned in this issue:

✅ Secrets from Vault/external-secrets-operator (via standard Kubernetes Secrets)
✅ Environment variables for tokens and credentials
✅ File mounts for TLS certificates
✅ GitOps-friendly (no credentials in ConfigMaps)
✅ Standard Kubernetes `env` syntax

Give it a try and let me know how it works for your use cases! If you run into any issues or have suggestions for improvements, please open a new issue.

Thanks again for your patience and detailed feedback!


I'll keep this issue open for few more days before closing it to allow for feedback 😄
