### ISSUE TITLE
[BUG] CRs Created Outside Operator Namespace

### ISSUE THREAD

**Issue by M4C4R** [AbdelrhmanHamouda/locust-k8s-operator#214]
**Describe the bug**
CRs (custom resources) can be created outside the operator namespace, but the operator lacks permissions to fulfill the requests as it attempts to create the jobs/services within the namespace of the CR.

> Exception occurred during Job creation: Failure executing: PATCH at: ... Message: jobs.batch "demo-test-master" is forbidden: User "system:serviceaccount:locust:locust-locust-k8s-operator" **cannot patch resource "jobs" in API group "batch" in the namespace "..."**.

> Exception occurred during Service deletion: Failure executing: DELETE at: ... Message: services "demo-test-master" is forbidden: User "system:serviceaccount:locust:locust-locust-k8s-operator" **cannot delete resource "services" in API group "" in the namespace "..."**.

**To Reproduce**
Steps to reproduce the behaviour:
1. Deploy the operator in namespace X
2. Create a locust test in namespace Y
3. Observe logs of operator

**Expected behaviour**
I expected the jobs/services to be created within the namespace of the operator, not of the CR. 

This is as granting the following at a cluster level is excessive:
```yaml
  - apiGroups: [ '*' ]
    resources:
      - services
    verbs:
      - get
      - list
      - create
      - update
      - delete
  - apiGroups: [ '*' ]
    resources:
      - jobs
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
```

**Additional context:**
We plan on bundling our locust tests with our application charts, so they will be deployed into the same namespace as the application - not the operator.
