### ISSUE TITLE
[BUG] Missing namespace for deployment

### ISSUE THREAD

**Issue by philipsabri** [AbdelrhmanHamouda/locust-k8s-operator#222]
**Describe the bug**
The `namespace` is not specified for the `deployment` resource, which results in the deployment being installed in the same namespace from which we are running kubectl. It is not inheriting the namespace label from the `helmCharts` configuration in Kustomize. For us, the `deployment` resource was deployed in the `default` namespace, while the other resources were deployed in the specified namespace.

**To Reproduce**
kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: locust-k8s-operator
    namespace: locust-ns
    includeCRDs: true
    releaseName: locust-k8s-operator
    version: v0.10.0
    repo: https://abdelrhmanhamouda.github.io/locust-k8s-operator
```
run `kustomize build --enable-helm > helm.yaml`
Inspect `helm.yaml` and see that the `namespace` was never added to the `deployment` resource. The same applies to the `rolebinding`, though I'm not sure if that is supposed to be like that.

**Expected behavior**
`namespace` should be added to the `deployment` resource

When deploying with Helm, this doesn't seem to be a problem, but with Kustomize, it is an issue since you are not always in the namespace you are deploying to, especially if you are deploying multiple charts from the same Kustomization file.

We had to temporary fix it with a patch

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: locust-k8s-operator
    namespace: locust-ns
    includeCRDs: true
    releaseName: locust-k8s-operator
    version: v0.10.0
    repo: https://abdelrhmanhamouda.github.io/locust-k8s-operator
    valuesInline:
      k8s:
        clusterRole:
          enabled: true
patches:
  - target:
      kind: Deployment
      name: locust-k8s-operator
    patch: |
      - op: add
        path: /metadata/namespace
        value: locust-ns
```
