### ISSUE TITLE
[Feature request] Inject kafka auth data based on a CR flag

### ISSUE THREAD

**Issue by AbdelrhmanHamouda** [AbdelrhmanHamouda/locust-k8s-operator#9]
To avoid having kafka auth info being injected to the pod all the time, allow this functionality to be controlled by a CR **optional** flag

Example: 
```yaml
apiVersion: locust.io/v1
kind: LocustTest
metadata:
  name: <CR_NAME>
spec:
  ...
  kafka: enabled | disabled (default: disabled)
```
